twig:
    file_name_pattern: '*.twig'
    form_themes:        ['bootstrap_5_layout.html.twig']
    globals:
        aws_endpoint: '%env(AWS_ENDPOINT)%'

when@test:
    twig:
        strict_variables: true
