name: Static Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, mbstring, xml, xmlwriter, tokenizer, json
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --no-interaction --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress --no-interaction --no-ansi --memory-limit=-1 --level=7 src tests